---
- name: copy template nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/{{domain}}.conf
    owner: nginx
    group: nginx
    mode: '0644'
  tags: 
    - runwithoffshoreip

- name: check syntax nginx
  shell: sudo nginx -t
  register: checksyntax
  tags: 
    - runwithoffshoreip

- name: reload nginx if check syntax ok
  shell: sudo nginx -s reload
  when: checksyntax.rc == 0
  tags: 
    - runwithoffshoreip

- name: update register email
  shell: /usr/bin/certbot register -m caotritran.14@gmail.com --agree-tos
  ignore_errors: true
  tags: 
    - runwithoffshoreip

- name: request certificate
  shell: /usr/bin/certbot --nginx -d '{{domain}}' --no-redirect --force-renewal
  register: result
  tags: 
    - runwithoffshoreip

- debug: var=result.stdout_lines
  tags: 
    - runwithoffshoreip
