---
- name: copy template nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/{{domain}}.conf
    owner: nginx
    group: nginx
    mode: '0644'
  tags: 
    - runwithoffshoreip

- name: check syntax nginx
  shell: sudo nginx -t
  register: checksyntax
  tags: 
    - runwithoffshoreip

- name: reload nginx if check syntax ok
  shell: sudo nginx -s reload
  when: checksyntax.rc == 0
  ignore_errors: true
  tags: 
    - runwithoffshoreip

- name: update register email
  shell: /usr/bin/certbot register -m caotritran.14@gmail.com --agree-tos
  ignore_errors: true
  tags: 
    - runwithoffshoreip

- name: stop nginx
  systemd:
    name: nginx
    state: stopped
  ignore_errors: yes
  tags: 
    - runwithoffshoreip

- name: make sure nginx stopped
  shell: sudo ps aux | grep nginx | grep -v grep | awk '{print $2}' | xargs kill -9
  ignore_errors: yes
  tags: 
    - runwithoffshoreip

- name: request certificate
  shell: /usr/bin/certbot --nginx -d '{{domain}}' --no-redirect --force-renewal
  register: result
  tags: 
    - runwithoffshoreip

- name: make sure nginx stopped
  shell: sudo ps aux | grep nginx | grep -v grep | awk '{print $2}' | xargs kill -9
  ignore_errors: yes
  tags: 
    - runwithoffshoreip

- name: stop nginx
  systemd:
    name: nginx
    state: started
  ignore_errors: yes
  tags: 
    - runwithoffshoreip

- debug: var=result.stdout_lines
  tags: 
    - runwithoffshoreip
