---
- name: copy template nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/{{domain}}.conf
    owner: nginx
    group: nginx
    mode: '0644'

- name: check syntax nginx
  shell: sudo nginx -t
  register: checksyntax

- name: reload nginx if check syntax ok
  shell: sudo nginx -s reload
  when: checksyntax.rc == 0

- name: update register email
  shell: /usr/bin/certbot register -m caotritran.14@gmail.com --agree-tos
  tags: register
  ignore_errors: yes

- name: request certificate
  shell: /usr/bin/certbot --nginx -d '{{domain}}' --no-redirect --force-renewal
  register: result

- debug: var=result.stdout_lines
