---
- name: copy scrip to remote host
  template:
    src: wp-cli.sh.j2
    dest: /tmp/wp-cli.sh
    mode: 755
  tags: 
    - runwithrootip

- name: run script
  shell: sudo bash /tmp/wp-cli.sh.sh
  ignore_errors: true
  register: wpcli
  tags: 
    - runwithrootip
  
- debug: var=wpcli.stdout_lines
  tags: 
    - runwithrootip